# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.define "development" do |dev|
    dev.vm.network "private_network", ip: "192.168.33.10"
    dev.vm.hostname = "dev"
    dev.vm.synced_folder "dev", "/vagrant"
  end
  config.vm.define "production" do |prod|
    prod.vm.network "private_network", ip: "192.168.33.11"
    prod.vm.hostname = "prod"
    dev.vm.synced_folder "prod", "/vagrant"
  end
end
